import { Injectable } from '@angular/core';
import { ObjectModelInitializer } from './ObjectModelInitializer';


@Injectable()
export class TextProperties {

  constructor(public objectModelInitializer: ObjectModelInitializer) {
  }

  getProperties(idioma) {
    let constant = this.objectModelInitializer.getConst();
    return {
      // Mensajes
      lbl_summary_info: idioma === constant.idiomaEs ? '¡Información!' : 'Info!',
      lbl_summary_success: idioma === constant.idiomaEs ? '¡Exitoso!' : 'Success!',
      lbl_summary_warning: idioma === constant.idiomaEs ? '¡Advertencia!' : 'Warning!',
      lbl_summary_danger: idioma === constant.idiomaEs ? '¡Error!' : 'Error!',
      lbl_summary_unknown_danger: idioma === constant.idiomaEs ? '¡Error Desconocido!' : 'Unknown Error!',
      lbl_detail_fue: idioma === constant.idiomaEs ? ' fue ' : ' has ',
      lbl_detail_el_registro: idioma === constant.idiomaEs ? 'El elemento #' : 'The element #',
      lbl_detail_el_registro_eliminado: idioma === constant.idiomaEs ? 'El elemento fue eliminado satisfactoriamente.' : 'The element was deleted successfully.',
      lbl_detail_creado: idioma === constant.idiomaEs ? 'creado' : 'created',
      lbl_detail_actualizado: idioma === constant.idiomaEs ? 'actualizado' : 'updated',
      lbl_detail_satisfactoriamente: idioma === constant.idiomaEs ? ' satisfactoriamente.' : ' successfully.',

      // Generales
      lbl_login: idioma === constant.idiomaEs ? 'Login' : 'Login',
      lbl_idioma: idioma === constant.idiomaEs ? 'Idioma' : 'Lenguage',
      lbl_activar_usuario: idioma === constant.idiomaEs ? 'Activar Usuario' : 'Activate User',
      lbl_categorias: idioma === constant.idiomaEs ? 'Categorías' : 'Categories',
      lbl_register: idioma === constant.idiomaEs ? 'Registro' : 'Register',
      lbl_responder: idioma === constant.idiomaEs ? 'Responder' : 'Reply',
      lbl_actualizar_usuario: idioma === constant.idiomaEs ? 'Actualizar Usuario' : 'Update User',
      lbl_posts_populares: idioma === constant.idiomaEs ? 'Posts Populares' : 'Populare Posts',
      lbl_colaboradores: idioma === constant.idiomaEs ? 'Colaboradores' : 'Collaborators',
      lbl_bienvenido: idioma === constant.idiomaEs ? 'Bienvenido' : 'Welcome',
      lbl_oficial_web_page: idioma === constant.idiomaEs ? 'Página Oficial de EUTANASIA' : 'Official Web Page of EUTANASIA',
      lbl_ref_foto_bio: idioma === constant.idiomaEs ? 'Biblioteca Pública Julio Pérez Ferrero, Cúcuta N/S' : 'Julio Pérez Ferrero Public Library, Cúcuta N / S',
      lbl_biografia_1: idioma === constant.idiomaEs ? "EUTANASIA, es una banda de Frenético Rock and Roll formada en Ocaña, Norte de Santander (Colombia) a finales del año 2013.  un grupo de amigos quizo rescatar los sonidos contundentes y crudos del Heavy Metal y Hard Rock de los 70's. Se Busca un sonido único que mantiene los riffs clásicos combinándolos con la potencia y el peso de las guitarras distorsionadas." : "EUTANASIA, is a Frenético Rock and Roll band formed in Ocaña, Norte de Santander (Colombia) at the end of 2013. A group of friends wanted to rescue the forceful and raw sounds of Heavy Metal and Hard Rock from the 70's. A unique sound is sought that maintains the classic riffs, combining them with the power and weight of distorted guitars.",
      lbl_biografia_2: idioma === constant.idiomaEs ? "Su mayor influenca musical son grupos como: AC/DC, Deep Purple, Led Zeppelin, Motorhead, Black Sabbath, entre otros. La música representa un descanso, liberar esa represión social que conlleva nuestra vida de gustos alternativos o diferentes. En analogía, es la Eutanasia a los problemas y señalamientos por estereotipos basados en gustos. Eutanasia es descansar, es liberarnos de lo cotidiano." : " His greatest musical influences are groups such as: AC / DC, Deep Purple, Led Zeppelin, Motorhead, Black Sabbath, among others. Music represents a break, releasing that social repression that our life entails with alternative or different tastes. In analogy, it is the Euthanasia to the problems and accusations by stereotypes based on tastes. Euthanasia is resting, it is freeing ourselves from the everyday.",
      lbl_biografia_3: idioma === constant.idiomaEs ? "La banda manda un mensaje a sus seguidores: 'Queremos aprovechar y agradecer a la gente que ha creído en nosotros y nos apoya en cada toque, evento, concierto, concurso. Gracias a todo el público que nos motiva a seguir en este sueño. Es un orgullo para nosotros representar a nuestra tierra.'" : "The band sends a message to its followers: 'We want to take advantage of and thank the people who have believed in us and support us in every touch, event, concert, contest. Thanks to all the public that motivates us to continue in this dream. We are proud to represent our land.'",
      lbl_biografia_2013_1: idioma === constant.idiomaEs ? "Su primer concierto se llevó a cabo la noche del 31 de Marzo de 2013, participando en 'Underground Rock II', coincidiendo con el lanzamiento de dos temas: 'Ya es tarde' y 'Eutanasia', esta última representando la identidad del grupo. En ese mismo año, el 28 de Septiembre, Eutanasia se presenta por primera vez fuera de la ciudad siendo invitados a la ciudad de Bucaramanga en el evento 'Tribute to the Gods' donde de igual forma se da la oportunidad de mostrar dos nuevos temas, 'Buscando Identidad' y 'Prestigio Fatal'. Poco más de un mes después, el 1 de Noviembre, el grupo hace presencia y participa en el 'Concurso de Bandas de Rock 2' donde logra el segundo puesto y asi posicionar a  Eutanasia como una banda reconocida e influyente dentro del Rock en Ocaña. Luego, el 21 de diciembre, Eutanasia se presenta en el evento 'Underground Rock III', convirtiéndose este en un año de oportunidades para la agrupación. Para cerrar el 2013, la banda se presentó en la “Rifa/Concierto” el 28 de Diciembre donde con el paso del tiempo, de ensayos y cada presentacion van encontrando el sonido que buscaban." : "His first concert was held on the night of March 31, 2013, participating in 'Underground Rock II', coinciding with the release of two songs: 'Ya es tarde' and 'Eutanasia', the latter representing the identity of the group. In that same year, on September, Eutnasia is presented in Bucaramanga at the event 'Tribute to the Gods' where in the same way, there is the opportunity to show two new themes, 'Buscando Identidad' and 'Prestigio Fatal'. This time there is a change in the members of the band, where Carlos Baene is introduced as the new Bass Player.",
      lbl_biografia_2014_1: idioma === constant.idiomaEs ? "El año 2014 fue uno de los mejores para la banda participando en diferentes eventos, nuevamente en Underground Rock IV, el cual se había constituido como el principal evento de rock de la ciudad. Ese mismo año volvieron al Concurso de Bandas III donde su guitarrista fue nombrado el mejor del evento." : "The year 2014 was one of the best for the band participating in different events, again at Underground Rock IV, which had become the main rock event in the city. That same year they returned to the Band Contest III where their guitarist was named the best of the event.",
      lbl_biografia_2014_2: idioma === constant.idiomaEs ? "A mediados de diciembre se lleva a cabo uno de los  festivales más importantes: 'La Guardia Fest' en el ecoparque de Comfanorte, en la capital del departamento. Esto fortalece a la banda e impulsa a que nuestra música  sea reconocida fuera de la ciudad." : "In mid-December one of the most important festivals takes place: 'La Guardia Fest' in the Comfanorte eco-park, in the capital of the department. This strengthens the band and encourages our music to be recognized outside of the city.",
      lbl_biografia_2015_1: idioma === constant.idiomaEs ? "Empezando 2015 se presentan en libélula bar en el evento 'Rock Night', en el que compartieron tarima con 4 bandas locales; Meses después fueron invitados a hacer parte de la integración universitaria de la Universidad Francisco de Paula Santander Ocaña (UFPSO)." : "Starting in 2015, they performed at the dragonfly bar at the 'Rock Night' event, where they shared the stage with 4 local bands; Months later they were invited to be part of the university integration of the Francisco de Paula Santander Ocaña University(UFPSO).",
      lbl_biografia_2015_2: idioma === constant.idiomaEs ? "Ahora que la banda está consolidada y con las baterías de rock recargadas, se empieza a tocar en bares de la ciudad para abrir puertas y participar en más eventos, con la oportunidad de ser organizadores en uno de ellos: 'Halloween Trick or Treat' llevado a cabo el 31 de Octubre." : "Now that the band is consolidated and with recharged rock batteries, they begin to play in bars in the city to open doors and participate in more events, with the opportunity to be organizers in one of them: 'Halloween Trick or Treat' led held on October 31st.",
      lbl_biografia_2016_1: idioma === constant.idiomaEs ? "Para el 2016 la banda graba su primer demo titulado ‘Frenético Rock And Roll’ el cual contiene 5 temas de su autoría grabados en La Guardia Estudio (Cúcuta); Gracias a ello se logra participar del compilado de Santander y Norte de Santander lanzado en formato casete: 'XIIIC-001 SANTANDER COALITION' al lado de bandas reconocidas de ambos departamentos." : "For 2016 the band records their first demo entitled ‘Frenético Rock And Roll’ which contains 5 songs of their authorship recorded in La Guardia Estudio (Cúcuta); Thanks to this, it is possible to participate in the compilation of Santander and Norte de Santander released in cassette format: 'XIIIC-001 SANTANDER COALITION' alongside recognized bands from both departments.",
      lbl_biografia_2016_2: idioma === constant.idiomaEs ? "En cuanto a presentaciones, en la ciudad de Ocaña se contó con la posibilidad de presentarse en la Plaza de Ferias para el 'Concierto de la fraternidad' al cual asistieron todos los Colegios del Municipio. Además hicieron parte del festival 'Catatumbo Rock Festival' en su primero edición llevado a cabo en Ocaña." : "Regarding presentations, in the city of Ocaña there was the possibility to appear in the Plaza de Ferias for the 'Concert of the fraternity' which was attended by all the Colleges of the Municipality. They were also part of the festival 'Catatumbo Rock Festival' in its first edition held in Ocaña.",
      lbl_biografia_2016_3: idioma === constant.idiomaEs ? "A nivel nacional se participa en convocatorias para eventos como el 'Viboral Rock' llegando hasta el último filtro (Quedando entre las 40 bandas finalistas seleccionadas de todo el país). También se presentan en el 'Somos Uno' en Cúcuta y el 'Rock al Parche 2' en Bucaramanga,  compartiendo tarima con bandas de gran trayectoria a nivel nacional." : "At the national level, they participate in calls for events such as the 'Viboral Rock' reaching the last filter (remaining among the 40 finalist bands selected from all over the country). They also perform at the 'Somos Uno' in Cúcuta and the 'Rock al Parche 2' in Bucaramanga, sharing the stage with bands of great national trajectory.",
      lbl_biografia_2017_1: idioma === constant.idiomaEs ? "Este año se participó en varios eventos en la ciudad de Cúcuta 'Possesed By Metal', 'Estridente Amanecer 2' y  el festival ‘Somos Uno’ donde se nota el gusto por la banda y siendo Cúcuta la ciudad que más ha brindado apoyo fuera de su terruño. En ese primer semestre son invitados a hacer parte del Pamplona Rock Festival, reconocido festival desde hace más de una década en la ciudad de la niebla; Una vez más expandiendo su sonido." : "This year we participated in several events in the city of Cúcuta 'Possesed By Metal', 'Estridente Amanecer 2' and the festival 'Somos Uno' where you can see the taste for the band and being Cúcuta the city that has provided the most support outside of its terroir. In that first semester they are invited to take part in the Pamplona Rock Festival, a recognized festival for more than a decade in the city of fog; Once again expanding its sound.",
      lbl_biografia_2018_1: idioma === constant.idiomaEs ? "De nuevo se hace parte del Catatumbo Rock Festival que se ha hecho importante en la ciudad, el cual en esta edición tuvo un enfoque social recaudando ayudas para niños en estado de vulnerabilidad. Por otro lado se participó en varios eventos locales apoyando la escena y mostrando nuevas piezas musicales." : "Once again, it is part of the Catatumbo Rock Festival that has become important in the city, which in this edition had a social focus, collecting aid for children in a state of vulnerability. On the other hand, they participated in several local events supporting the scene and showing new musical pieces.",
      lbl_biografia_2019_1: idioma === constant.idiomaEs ? "Por primera vez, Bogotá; el 6 de abril del año en mención eutanasia pisa la capital Colombiana, es invitado a presentarse junto a bandas capitalinas y a la exigencia de un nuevo público; Gracias a esta experiencia se dio a conocer aún más el demo y de igual manera presentar los temas que no habían salido a la luz. Tuvieron otras presentaciones en su ciudad, incluida la presentación cultural en apoyo al paro nacional." : "For the first time, Bogotá; On April 6 of the year in mention of euthanasia he steps on the Colombian capital, he is invited to appear together with capital bands and to the demand of a new public; Thanks to this experience, the demo was made known even more and also presented the songs that had not come to light. They had other presentations in their city, including the cultural presentation in support of the national strike.",
      lbl_biografia_2020_1: idioma === constant.idiomaEs ? "En este año pandémico tan difícil para muchos artistas surgieron nuevas ideas y alternativas; en nuestro caso trabajamos en nuevos temas y realizamos un video clip de un tema inédito de la banda el cual será lanzado este 31 de diciembre por nuestra página en el siguiente enlace." : "In this difficult pandemic year for many artists, new ideas and alternatives emerged; In our case, we work on new songs and we make a video clip of an unreleased song by the band which will be released on December 31 through our page at the following link.",
      lbl_info_sin_resultados: idioma === constant.idiomaEs ? 'Sin Resultados' : 'Without Results',
      lbl_info_fallo_conectar_base_datos: idioma === constant.idiomaEs ? 'No hay Conexión a la Base de Datos' : 'Without Conection to Data Base',
      lbl_info_cargando_resultados: idioma === constant.idiomaEs ? 'Cargando Resultados' : 'Loading Results',
      lbl_info_proceso_completo: idioma === constant.idiomaEs ? 'Proceso realizado satisfactoriamente' : 'Process complete',
      lbl_error_403: idioma === constant.idiomaEs ? '403' : '403',
      lbl_error_404: idioma === constant.idiomaEs ? '404' : '404',
      lbl_error_500: idioma === constant.idiomaEs ? '500' : '500',
      lbl_mensaje_error_404: idioma === constant.idiomaEs ? 'La página que busca no ha sido encontrada.' : 'Page Not Found.',
      lbl_oops: idioma === constant.idiomaEs ? '¡Oops!' : 'Oops!',
      lbl_vencimiento_token_sesion: idioma === constant.idiomaEs ? 'Fecha de Vencimiento del Token: ' : 'Token Expiration Date',
      lbl_vcode_expiro: idioma === constant.idiomaEs ? 'El Código de Verificación ya expiró.' : 'The Verification Code has expired.',
      lbl_ir_a: idioma === constant.idiomaEs ? 'Ir a: ' : 'Go to: ',
      lbl_ir_inicio: idioma === constant.idiomaEs ? 'Ir al Login' : 'Go to Login',
      lbl_btn_olvidaste_tu_clave: idioma === constant.idiomaEs ? '¿Olvidaste tu Clave?' : 'Do You forget your Password?',
      lbl_btn_restaurar_clave: idioma === constant.idiomaEs ? 'Restaurar Clave' : 'Restore Password',
      lbl_btn_no_ha_llegado_correo_vcode: idioma === constant.idiomaEs ? '¿No ha llegado ningún Correo? Presiona para Reintentar.' : 'No mail has arrived? Press to Retry.',
      lbl_drag_archivos: idioma === constant.idiomaEs ? 'Haga [Clic] o arrastre un archivo aquí' : 'Click or Drag a file here',
      lbl_cantidad_max_archivos: idioma === constant.idiomaEs ? 'Cantidad máxima: 5 archivos' : 'Only 5 Files',
      lbl_galeria_media: idioma === constant.idiomaEs ? 'Galería y Multimedia' : 'Gallery and Media',
      lbl_eutanasicos: idioma === constant.idiomaEs ? 'Eutanásicos' : 'Euthanasian',
      lbl_participaciones: idioma === constant.idiomaEs ? 'Participaciones' : 'Participations',
      lbl_proximo_evento: idioma === constant.idiomaEs ? 'Próximo Evento' : 'Next Event',
      lbl_posts: idioma === constant.idiomaEs ? 'Posts' : 'Posts',
      lbl_registro_ingreso: idioma === constant.idiomaEs ? 'Registro/Ingreso' : 'Register/Login',
      lbl_por_definir: idioma === constant.idiomaEs ? 'Por definir' : 'To define',
      lbl_comparte: idioma === constant.idiomaEs ? 'Compartí' : 'Share',
      lbl_blog: idioma === constant.idiomaEs ? 'Blog' : 'Blog',
      lbl_timeline: idioma === constant.idiomaEs ? 'Timeline' : 'Timeline',
      lbl_post_interes: idioma === constant.idiomaEs ? 'Posts de interés' : 'Posts of interest',
      lbl_bio: idioma === constant.idiomaEs ? 'Biografía' : 'Biography',
      lbl_inicio: idioma === constant.idiomaEs ? 'Inicio' : 'Start',
      lbl_ultimas_publicaciones: idioma === constant.idiomaEs ? 'Últimas Publicaciones' : 'Latest Posts',
      lbl_contacto: idioma === constant.idiomaEs ? 'Contacto' : 'Contact',
      lbl_leer_mas: idioma === constant.idiomaEs ? 'Leer Más...' : 'Read more...',
      lbl_disenador_grafico: idioma === constant.idiomaEs ? 'Diseñador Gráfico' : 'Graphic Designer',
      lbl_estudio_grabacion: idioma === constant.idiomaEs ? 'Estudio de Grabación' : 'Recording Studio',
      lbl_mensaje_agrega_comentario: idioma === constant.idiomaEs ? 'Agrega tu comentario (máximo 500 caracteres)' : 'Add your comment (max 500 chars)',
      lbl_comentarios: idioma === constant.idiomaEs ? 'Comentarios' : 'Comments',
      lbl_autor: idioma === constant.idiomaEs ? 'Autor' : 'Author',
      lbl_link_f: idioma === constant.idiomaEs ? 'Enlace Facebook' : 'Link Facebook',
      lbl_link_i: idioma === constant.idiomaEs ? 'Enlace Instagram' : 'Link Instagram',
      lbl_link_g: idioma === constant.idiomaEs ? 'Enlace Google' : 'Link Google',
      lbl_link_t: idioma === constant.idiomaEs ? 'Enlace Twitter' : 'Link Twitter',
      lbl_noticias: idioma === constant.idiomaEs ? 'Noticias' : 'News',

      // Banda
      lbl_banda: idioma === constant.idiomaEs ? 'Banda' : 'Band',
      lbl_banda_frenetico_rock_and_roll: idioma === constant.idiomaEs ? 'Frenético Rock and Roll' : 'Frenzy Rock and Roll',
      lbl_banda_descripcion_demo: idioma === constant.idiomaEs ? 'Este es el primer Demo de la banda. Temática de metamorfosis en el pensamiento crítico y en la influencia musical en la vida diaria. Esto es dedicado a todas esas personas que quieren descansar, pero no lo pueden expresar: ¡Eutanasia Para Todos!' : 'This is the first demo of the band. Metamorphosis theme in critical thinking and musical influence on daily life. This is dedicated to all those people who want to rest, but cannot express it: Eutanasia for All!',
      lbl_compilado_santander_coalition: idioma === constant.idiomaEs ? 'Compilación Santander Coalition - Lado D' : 'Santander Coalition - Side D',
      lbl_banda_descripcion_compilado: idioma === constant.idiomaEs ? 'Compilado realizado en el año 2016. Colombian Label & Distro. XIIIC-001 XII CANDLES COMPILATION.' : 'Compiled in 2016. Colombian Label & Distro. XIIIC-001 XII CANDLES COMPILATION.',
      lbl_entrevista_cultura_subterranea: idioma === constant.idiomaEs ? 'Entrevista Cultura Subterránea' : 'Underground Culture Interview',
      lbl_banda_descripcion_cultura_subterranea: idioma === constant.idiomaEs ? 'Realizado en la ciudad de Bucaramanga, año 2017.' : 'Made in the city of Bucaramanga, year 2017.',
      lbl_banda_demo_1: idioma === constant.idiomaEs ? 'Ya es tarde' : 'Ya es tarde',
      lbl_banda_demo_2: idioma === constant.idiomaEs ? 'Buscando identidad' : 'Buscando identidad',
      lbl_banda_demo_3: idioma === constant.idiomaEs ? 'Prestigio fatal' : 'Prestigio fatal',
      lbl_banda_demo_4: idioma === constant.idiomaEs ? 'De vuelta al infierno' : 'De vuelta al infierno',
      lbl_banda_demo_5: idioma === constant.idiomaEs ? 'No moriré' : 'No moriré',
      lbl_banda_pedro: idioma === constant.idiomaEs ? 'Pedro Sánchez' : 'Pedro Sánchez',
      lbl_banda_pipe: idioma === constant.idiomaEs ? 'Andrés Sánchez' : 'Andrés Sánchez',
      lbl_banda_leo: idioma === constant.idiomaEs ? 'Leo Navarro' : 'Leo Navarro',
      lbl_banda_carlos: idioma === constant.idiomaEs ? 'Carlos Baene' : 'Carlos Baene',
      lbl_banda_vocalista: idioma === constant.idiomaEs ? 'Vocalista' : 'Vocalist',
      lbl_banda_guitarrista: idioma === constant.idiomaEs ? 'Guitarrista' : 'Guitarist',
      lbl_banda_bajista: idioma === constant.idiomaEs ? 'Bajista' : 'Bassist',
      lbl_banda_baterista: idioma === constant.idiomaEs ? 'Baterista' : 'Drummer',
      lbl_banda_carlos_jacome: idioma === constant.idiomaEs ? 'Carlos Jácome' : 'Carlos Jácome',
      lbl_banda_guardia_estudio: idioma === constant.idiomaEs ? 'La Guardia Estudio' : 'La Guardia Estudio',
      lbl_banda_resena_guardia_fest: idioma === constant.idiomaEs ? 'La Guardia Estudio se desempeña en actividades de grabación de sonido y edición de música, creación musical y actividades de espectáculos musicales en vivo.' : 'La Guardia Estudio works in sound recording and music editing activities, music creation and live music entertainment activities.',
      lbl_banda_resena_carlos_jacome: idioma === constant.idiomaEs ? 'Apasionado por la música, el arte y el diseño, me he desempeñado profesionalmente en Agencias de Publicidad & Diseño y en la parte académica como docente, trabajos de ilustración para portadas de cds, libros, revistas, proyectos de identidad gráfica corporativa y diseño editorial.' : 'Passionate about music, art and design, I have worked professionally in Advertising & Design Agencies and in the academic part as a teacher, illustration work for CD covers, books, magazines, corporate graphic identity projects and editorial design.',
      lbl_banda_ayuda_compartir: idioma === constant.idiomaEs ? 'Ayúdanos a compartir nuestra música a todo el mundo' : 'Help us share our music with everyone',
      lbl_banda_resena_bajista: idioma === constant.idiomaEs ? 'Bajista de rock/metal nacido en Bucaramanga, el segundo y actual bajista de la banda, conocido por la energía que desborda al tocar en vivo y la técnica musical en las canciones, muchos consideran importante este gesto, ya que motiva al público y no es común en bajistas la movilidad en el escenario.' : 'Rock/metal bassist born in Bucaramanga, the second and current bassist of the band, known for the energy that overflows when playing live and the musical technique in the songs, many consider this gesture important, since it motivates the public and not mobility on stage is common for bass players.',
      lbl_banda_resena_baterista: idioma === constant.idiomaEs ? 'Baterista de rock nacido en Ocaña, el segundo y actual baterista de la banda, conocido por la alegría que expresa, siempre intentando proyectar espiritualmente la banda. Musicalmente sus ritmos son influenciados por muchos géneros incluso fuera del rock lo que amplía la posibilidad de crear sets con autenticidad.' : 'Rock drummer born in Ocaña, the second and current drummer of the band, known for the joy he expresses, always trying to spiritually project the band. Musically their rhythms are influenced by many genres even outside of rock, which broadens the possibility of creating sets with authenticity.',
      lbl_banda_resena_guitarrista: idioma === constant.idiomaEs ? 'Guitarrista lider de la banda ocañera Eutanasia, conocido por su humildad y su locura, es una persona que tiene conocimiento musical del rock  lo cuál permite enseñanzas constantes para todos. Su papel es crucial para encontrar una identidad propia .' : 'Rock main guitarist and co-founder of the band Eutanasia from Ocaña, known for his humility and his madness, he is a person who has musical knowledge of rock which allows constant teachings for everyone. Your role is crucial to find your own identity.',
      lbl_banda_resena_vocalista: idioma === constant.idiomaEs ? 'Vocalista Ocañero de Eutanasia banda de Frenético Rock and Roll. Amante de la buena música y de los sonidos del rock clásico. Su puesta en escena se caracteriza por su agresividad y crudeza en la voz, además garantiza máxima interacción con el público. \"El Rock para mí no es una moda, es un sentimiento que nunca podré dejar\"' : 'Vocalist from Ocaña of Eutanasia Frenético Rock and Roll band. Lover of good music and the sounds of classic rock. Its staging is characterized by its aggressiveness and rawness in the voice, it also guarantees maximum interaction with the public. \"Rock for me is not a fad, it is a feeling that I can never put down\"',

      // Mensajes
      lbl_mensaje_archivo_subido: idioma === constant.idiomaEs ? 'Archivo(s) subido correctamente.' : 'File(s) uploaded successfully.',
      lbl_mensaje_cant_archivos_permitidos: idioma === constant.idiomaEs ? 'La cantidad de archivos por subir supera la cantidad permitida.' : 'The number of files to upload exceeds the allowed number.',
      lbl_mensaje_cant_archivos_permitidos_detalle: idioma === constant.idiomaEs ? 'Máximo {0} archivo(s).' : 'Limit is {0} at most.',
      lbl_mensaje_dropzone_principal: idioma === constant.idiomaEs ? 'Esta es una zona de carga de archivos' : 'This is a file upload area.',
      lbl_mensaje_dropzone_secundario: idioma === constant.idiomaEs ? 'Arrastre su archivo o dé [Clic] para subir uno desde el explorador de archivos' : 'Drag your file or Click to upload one from file explorer.',
      lbl_mensaje_size_archivos_permitidos: idioma === constant.idiomaEs ? 'Error con el tamaño del archivo: ' : 'File size error: ',
      lbl_mensaje_size_archivos_permitidos_detalle: idioma === constant.idiomaEs ? 'El tamaño del archivo excede lo permitido. El máximo es ' : 'The file size exceeds what is allowed. Maximum upload size is ',
      lbl_mensaje_tipo_archivos_permitidos_generico: idioma === constant.idiomaEs ? 'El tipo del archivo o elemento no es permitido.' : 'The file or element type is not allowed.',
      lbl_mensaje_tipo_archivos_permitidos: idioma === constant.idiomaEs ? 'Error con el tipo del archivo: ' : 'File type error: ',
      lbl_mensaje_tipo_archivos_permitidos_detalle: idioma === constant.idiomaEs ? 'El tipo del archivo no es permitido. Se permiten {0}.' : 'The file type is not allowed. Allowed file types {0}.',
      lbl_mensaje_archivo_no_subido: idioma === constant.idiomaEs ? 'El archivo no pudo ser procesado.' : 'The file could not be processed.',
      lbl_mensaje_seleccione_archivo_para_subir: idioma === constant.idiomaEs ? 'Seleccione un archivo.' : 'Select a file.',
      lbl_mensaje_no_conexion_servidor: idioma === constant.idiomaEs ? 'No se ha podido establecer la conexión con el Servidor en algun proceso interno' : 'The connection to the Server could not be established in some internal process',
      lbl_mensaje_login_invalido: idioma === constant.idiomaEs ? 'El Usuario y/o la Contraseña son incorrectos' : 'The User and/or Password are incorrect',
      lbl_mensaje_sin_detalles_error: idioma === constant.idiomaEs ? 'No hay detalles del error' : 'No error details',
      lbl_mensaje_error_403_ingresar_ruta: idioma === constant.idiomaEs ? 'Está intentando ingresar a la ruta: ' : '',
      lbl_mensaje_error_403_no_permisos: idioma === constant.idiomaEs ? 'No cuenta con permisos para visualizar el contenido.' : 'You do not have permissions to view its content.',
      lbl_mensaje_error_403_sesion_expirada: idioma === constant.idiomaEs ? 'Su sesión ha expirado. Debe ingresar de nuevo a la aplicación.' : 'Your session has expired. You must enter the application again.',
      lbl_mensaje_error_500_no_sesion: idioma === constant.idiomaEs ? 'No tiene una Sesión Iniciada.' : 'You dont have a session started.',
      lbl_mensaje_file_detail_size: idioma == constant.idiomaEs ? 'El archivo seleccionado supera el límite de tamaño permitido' : 'The selected file exceeds the allowed size limit',
      lbl_mensaje_file_detail_type: idioma == constant.idiomaEs ? 'El archivo seleccionado no cumple con la extensión permitida' : 'The selected file does not meet the allowed extension',
      lbl_mensaje_file_toolbar: idioma == constant.idiomaEs ? 'Seleccione los archivos que desea adjuntar con su respectiva observación' : 'Select the files you want to attach with their respective observation',
      lbl_mensaje_file_selected: idioma == constant.idiomaEs ? 'Archivo seleccionado' : 'File selected',
      lbl_mensaje_password_no_coincide: idioma == constant.idiomaEs ? 'Las claves no coinciden' : 'The password no match',
      lbl_mensaje_password_confirmar: idioma == constant.idiomaEs ? 'Debe confirmar la clave' : 'You must confirm password',
      lbl_mensaje_debe_ser_usuario_logueado: idioma == constant.idiomaEs ? 'Debe ser usuario logueado para acceder al contenido.' : 'You must be a logged in user to access the content.',
      lbl_mensaje_vacio: idioma == constant.idiomaEs ? 'Valor Vacío.' : 'Empty Value.',
      lbl_mensaje_incorrecto: idioma == constant.idiomaEs ? 'Valor Incorrecto.' : 'Incorrect Value.',
      lbl_mensaje_no_info_select: idioma == constant.idiomaEs ? 'No hay información para mostrar' : 'No info to show',
      lbl_mensaje_usuario_activado: idioma === constant.idiomaEs ? 'Se ha activado exitosamente el usuario.' : 'The user has been successfully activated.',
      lbl_mensaje_usuario_no_encontrado: idioma === constant.idiomaEs ? 'No se ha encontrado el usuario.' : 'The user was not found.',
      lbl_mensaje_usuario_no_activado: idioma === constant.idiomaEs ? 'No se pudo activar el usuario.' : 'The user could not be activated.',
      lbl_mensaje_clave_actualizada_ok: idioma === constant.idiomaEs ? 'Clave actualizada con éxito.' : ' Password updated succesfully.',
      lbl_mensaje_digite_nueva_clave: idioma === constant.idiomaEs ? 'Digite la nueva Clave.' : 'Enter the new password.',
      lbl_mensaje_nueva_promo: idioma === constant.idiomaEs ? 'Cuando el reloj llegue a cero se mostrará el nuevo contenido para usuarios registrados.' : 'When the clock reaches zero the new content will be displayed for registered users.',
      lbl_mensaje_nueva_promo_activo: idioma === constant.idiomaEs ? 'Te presentamos lo último de Eutanasia:' : 'We present you the latest of Eutanasia:',
      lbl_mensaje_usuario_creado: idioma === constant.idiomaEs ? 'El usuario ha sido creado con éxito. Se ha enviado a su correo electrónico el enlace de activación para que pueda disfrutar del contenido.' : 'The user has been created successfully. The activation link has been sent to your email so that you can enjoy the content.',
      lbl_mensaje_usuario_modificado: idioma === constant.idiomaEs ? 'El usuario ha sido actualizado con éxito.' : 'The user has been updated successfully.',
      lbl_mensaje_debe_estar_logueado: idioma === constant.idiomaEs ? 'Debe ser usuario eutanásico registrado para ver el contenido.' : 'You must be a registered euthanasian user to view the content.',

      // Modales
      lbl_info_titulo_modal_error: idioma === constant.idiomaEs ? 'ERROR' : 'ERROR',
      lbl_info_titulo_modal_informacion: idioma === constant.idiomaEs ? 'INFORMACION' : 'INFORMATION',
      lbl_info_titulo_modal_advertencia: idioma === constant.idiomaEs ? 'ADVERTECNIA' : 'WARNING',
      lbl_info_titulo_modal_proceso_exitoso: idioma === constant.idiomaEs ? 'PROCESO EXITOSO' : 'PROCESS COMPLETE',

      // Steps
      lbl_info_titulo_step_personal: idioma === constant.idiomaEs ? 'PERSONAL' : 'PERSONAL',
      lbl_info_titulo_step_identificacion: idioma === constant.idiomaEs ? 'IDENTIFICACIÓN' : 'IDENTIFICATION',
      lbl_info_titulo_step_seguridad: idioma === constant.idiomaEs ? 'SEGURIDAD' : 'SECURITY',
      lbl_info_titulo_step_confirmacion: idioma === constant.idiomaEs ? 'CONFIRMACION' : 'CONFIRMATION',

      // Menu
      lbl_menu_parametrizacion: idioma === constant.idiomaEs ? 'Parametrización' : 'Parameterization',
      lbl_menu_sesion: idioma === constant.idiomaEs ? 'Sesión' : 'Session',
      lbl_menu_usuario: idioma === constant.idiomaEs ? 'Usuarios' : 'Users',
      lbl_menu_tercero: idioma === constant.idiomaEs ? 'Empresas/Terceros' : 'Companies',
      lbl_menu_sala: idioma === constant.idiomaEs ? 'Salas de Ensayo' : 'Rehearsal Rooms',
      lbl_menu_ubicacion: idioma === constant.idiomaEs ? 'Ubicaciones' : 'Locations',
      lbl_menu_banda_integrante: idioma === constant.idiomaEs ? 'Bandas/Integrantes' : 'Bands/Members',
      lbl_menu_ensayo: idioma === constant.idiomaEs ? 'Agendar Ensayo' : 'Schedule Rehearsal',
      lbl_menu_factura_pago: idioma === constant.idiomaEs ? 'Facturas/Pagos' : 'Bills/Payments',
      lbl_menu_inventario: idioma === constant.idiomaEs ? 'Productos/Accesorios' : 'Products/Accesories',
      lbl_menu_prestamo: idioma === constant.idiomaEs ? 'Alquiler' : 'Rental',

      // Acciones
      lbl_btn_nuevo: idioma === constant.idiomaEs ? 'Nuevo' : 'New',
      lbl_btn_ingresar: idioma === constant.idiomaEs ? 'Ingresar' : 'Sign In',
      lbl_btn_registrarse: idioma === constant.idiomaEs ? 'Registrarse' : 'Register',
      lbl_btn_inicio: idioma === constant.idiomaEs ? 'Inicio' : 'Login',
      lbl_btn_consultar: idioma === constant.idiomaEs ? 'Consultar' : 'Query',
      lbl_btn_comentar: idioma === constant.idiomaEs ? 'Comentar' : 'Comment',
      lbl_btn_crear: idioma === constant.idiomaEs ? 'Crear' : 'Create',
      lbl_btn_editar: idioma === constant.idiomaEs ? 'Editar' : 'Edit',
      lbl_btn_limpiar: idioma === constant.idiomaEs ? 'Limpiar' : 'Clean',
      lbl_btn_atras: idioma === constant.idiomaEs ? 'Atrás' : 'Back',
      lbl_btn_masivo: idioma === constant.idiomaEs ? 'Masivo' : 'Masive',
      lbl_btn_exportar: idioma === constant.idiomaEs ? 'Exportar' : 'Export',
      lbl_btn_importar: idioma === constant.idiomaEs ? 'Importar' : 'Import',
      lbl_btn_actualizar: idioma === constant.idiomaEs ? 'Actualizar' : 'Update',
      lbl_btn_guardar: idioma === constant.idiomaEs ? 'Guardar' : 'Save',
      lbl_btn_ite_remover: idioma === constant.idiomaEs ? 'Remover' : 'Remove',
      lbl_btn_ite_agregar: idioma === constant.idiomaEs ? 'Agregar' : 'Add',
      lbl_btn_siguiente: idioma === constant.idiomaEs ? 'Siguiente' : 'Next',
      lbl_btn_anterior: idioma === constant.idiomaEs ? 'Anterior' : 'Back',
      lbl_btn_cancelar: idioma === constant.idiomaEs ? 'Cancelar' : 'Cancel',
      lbl_btn_subir: idioma === constant.idiomaEs ? 'Subir' : 'Upload',
      lbl_btn_escoger: idioma === constant.idiomaEs ? 'Escoger' : 'Choose',
      lbl_btn_escoger_archivo: idioma === constant.idiomaEs ? 'Escoger Archivo' : 'Choose File',
      lbl_subir_archivos: idioma === constant.idiomaEs ? 'Subir Archivos' : 'Upload Files',
      lbl_btn_subir_archivos: idioma == constant.idiomaEs ? 'Subir Archivos' : 'Upload Files',
      lbl_btn_enviar_email: idioma == constant.idiomaEs ? 'Enviar E-Mail' : 'Send E-Mail',

      // Header
      lbl_header_usuario: idioma === constant.idiomaEs ? 'Usuario' : 'User',
      lbl_header_clave: idioma === constant.idiomaEs ? 'Clave' : 'Password',
      lbl_header_repetir_clave: idioma === constant.idiomaEs ? 'Repetir Clave' : 'Repeat Password',
      lbl_header_nombre: idioma === constant.idiomaEs ? 'Nombres' : 'Names',
      lbl_header_apellido: idioma === constant.idiomaEs ? 'Apellidos' : 'surnames',
      lbl_header_correo: idioma === constant.idiomaEs ? 'Correo' : 'E-Mail',
      lbl_header_resena: idioma === constant.idiomaEs ? 'Reseña' : 'Review',
      lbl_header_fecha_nacimiento: idioma === constant.idiomaEs ? 'Fecha Nacimiento' : 'Birth Date',

      // Titles
      lbl_mtto_consulta: idioma === constant.idiomaEs ? 'Consulta' : 'Query',
      lbl_mtto_creacion_edicion: idioma === constant.idiomaEs ? 'Creación/Edición' : 'Create/Edit',

      // Tooltips
      lbl_tip_cerrar_sesion: idioma === constant.idiomaEs ? 'Cerrar Sesión' : 'End Session',
      lbl_tip_agregar: idioma === constant.idiomaEs ? '[Clic] para agregar un nuevo registro' : 'Click to add a new register',
      lbl_tip_editar: idioma === constant.idiomaEs ? '[Clic] para editar registro' : 'Click to edit the register selected',
      lbl_tip_eliminar: idioma === constant.idiomaEs ? '[Clic] para eliminar registro' : 'Click to delete the register selected',
      lbl_tip_buscar: idioma === constant.idiomaEs ? '[Clic] para buscar registros' : 'Click to search registers',
      lbl_tip_limpiar: idioma === constant.idiomaEs ? '[Clic] para limpiar' : 'Click to clean',
      lbl_tip_anterior: idioma === constant.idiomaEs ? '[Clic] para regresar' : 'Click to go back',
      lbl_tip_actualizar: idioma === constant.idiomaEs ? '[Clic] para actualizar' : 'Click to update',
      lbl_tip_guardar: idioma === constant.idiomaEs ? '[Clic] para guardar' : 'Click to save',
      lbl_tip_exportar_datos: idioma === constant.idiomaEs ? '[Clic] para exportar' : 'Click to export',
      lbl_tip_subir_archivos: idioma === constant.idiomaEs ? '[Clic] para subir archivos' : 'Click to upload files',
      lbl_tip_eliminar_archivo: idioma === constant.idiomaEs ? '[Clic] para eliminar archivo' : 'Click to delete file',
      lbl_tip_mostrar_ocultar_archivos: idioma === constant.idiomaEs ? '[Clic] para mostrar/ocultar archivos' : 'Click to show/hide files',

      //Enums
      lbl_enum_generico_valor_vacio: idioma === constant.idiomaEs ? 'Selecciona una opción' : 'Select a Item',

      lbl_enum_si: idioma === constant.idiomaEs ? 'Si' : 'Yes',
      lbl_enum_no: idioma === constant.idiomaEs ? 'No' : 'No',

      lbl_enum_sexo_valor_masculino: idioma === constant.idiomaEs ? 'Masculino' : 'Male',
      lbl_enum_sexo_valor_femenino: idioma === constant.idiomaEs ? 'Femenino' : 'Female',
      lbl_enum_sexo_valor_otro: idioma === constant.idiomaEs ? 'Otro' : 'Other',

      lbl_enum_rol_usuario_valor_administrador: idioma === constant.idiomaEs ? 'Administrador' : 'Admin',
      lbl_enum_rol_usuario_valor_fan: idioma === constant.idiomaEs ? 'Fan' : 'Fan',
      lbl_enum_rol_usuario_valor_contacto_laboral: idioma === constant.idiomaEs ? 'Contacto Laboral' : 'Work Contact',

      lbl_enum_estado_valor_usuario_inactivo: idioma === constant.idiomaEs ? 'Inactivo' : 'Inactive',
      lbl_enum_estado_valor_usuario_activo: idioma === constant.idiomaEs ? 'Activo' : 'Active',
      lbl_enum_estado_valor_usuario_rechazado: idioma === constant.idiomaEs ? 'Rechazado' : 'Rejected',

      lbl_enum_categoria_valor_invitacion_evento: idioma === constant.idiomaEs ? 'Invitación Evento' : 'Event Invitation',
      lbl_enum_categoria_valor_agradecimientos_saludos: idioma === constant.idiomaEs ? 'Agradecimientos y Saludos' : 'Thanks and Greetings',
      lbl_enum_categoria_valor_criticas: idioma === constant.idiomaEs ? 'Críticas' : 'Critics',
      lbl_enum_categoria_valor_frenetico_rnr: idioma === constant.idiomaEs ? 'Frenético Rock n Roll' : 'Frenzy Rock n Roll',
      lbl_enum_categoria_valor_noticias_mundiales: idioma === constant.idiomaEs ? 'Noticias Mundiales' : 'World News',

      // Módulos Genéricos
      lbl_mtto_generico_activo: idioma === constant.idiomaEs ? 'Activo' : 'Active',
      lbl_mtto_generico_step_1_registrar_usuario: idioma === constant.idiomaEs ? 'Registre su Información Personal' : 'Register your Personal Information.',
      lbl_mtto_generico_step_2_registrar_usuario: idioma === constant.idiomaEs ? 'Registre su Información de Identificación' : 'Register your Identification Information.',
      lbl_mtto_generico_step_3_registrar_usuario: idioma === constant.idiomaEs ? 'Cree su nuevo Usuario' : 'Create your new user.',
      lbl_mtto_generico_step_4_registrar_usuario: idioma === constant.idiomaEs ? 'Ingrese el código de verificación que se ha enviado a su correo para Activar la Cuenta.' : 'Enter the verification code that sent your email to activate the account.',
      lbl_mtto_generico_step_registrar_usuario_error: idioma === constant.idiomaEs ? 'Los datos suministrados en este Paso son incorrectos. Verifique la información.' : 'The data provided in this step is incorrect. Check the information.',
      lbl_mtto_generico_codigo_verificaicion_enviado_ok: idioma === constant.idiomaEs ? 'Se ha enviado el Código de Verificación de Cuenta correctamente.' : 'The Account Verification Code has been sent correctly.',
      lbl_mtto_generico_opinion: idioma === constant.idiomaEs ? 'Tu opinión es importante para nosotros' : 'Your opinion is important to us',

      // Módulos Posts
      lbl_mtto_post: idioma === constant.idiomaEs ? 'Posts' : 'Posts',
      lbl_mtto_post_titulo: idioma === constant.idiomaEs ? 'Título' : 'Title',
      lbl_mtto_post_subtitulo: idioma === constant.idiomaEs ? 'Subtítulo' : 'Subtitle',
      lbl_mtto_post_articulo: idioma === constant.idiomaEs ? 'Artículo' : 'Arrticle',
      lbl_mtto_post_tags: idioma === constant.idiomaEs ? 'Tags' : 'Tags',
      lbl_mtto_post_categoria: idioma === constant.idiomaEs ? 'Categoría' : 'Category',

      // Módulos Enviar EMail
      lbl_mtto_email_mensaje: idioma === constant.idiomaEs ? 'Mensaje' : 'Message',
      lbl_mtto_email_para: idioma === constant.idiomaEs ? 'Destinatarios' : 'Receivers',
      lbl_mtto_email_correo_remite: idioma === constant.idiomaEs ? 'Correo Remitente' : 'Sender Email',
      lbl_mtto_email_nombre_remite: idioma === constant.idiomaEs ? 'Nombre Remitente' : 'Sender Name',
      lbl_mtto_email_asunto: idioma === constant.idiomaEs ? 'Asunto' : 'Subject',

    }
  };
}